world:
  name: "procedural_world"
  seed: 1
  width: 20.0        # meters
  height: 20.0
  cell_size: 1.


objects:

  big_pillar:
    model_path: "big_pillar"
    obstacle_config_path: "big_pillar/obstacle_config.yaml"

  pillar:
    model_path: "pillar"
    obstacle_config_path: "pillar/obstacle_config.yaml"





  # box:
  #   model_path: "box"
  #   obstacle_config_path: "box/obstacle_config.yaml"
  #   # grid_shape: [[0, 0]]  # for complex shapes (other than rectangular footprint) you can specify the grid cells occupied by the object, starting from the center cell [[0,0]]

  # stacked_boxes:
  #   model_path: "stacked_boxes/model.sdf"
  #   obstacle_config_path: "stacked_boxes/obstacle_config.yaml"