world:
  seed: 1
  width: 20.0        # meters
  height: 20.0
  cell_size: 1.
  
objects:
  box:
    model_path: "../models/box/model.sdf"
    weight: 2                 # optional weighting factor for random selection

  stacked_boxes:
    model_path: "../models/stacked_boxes/model.sdf"
    weight: 2                 # optional weighting factor for random selection
